apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
  spec:
    containers:
     - name: alpine
     image: alpine
     command: ["/bin/sh", "-c"]
       args:
         - while true; do echo "$(cat /config/name)"; sleep 5; done
     volumeMounts:
     - name: config-volume
     mountPath: /config
     volumes:
     - name: config-volume
      configMap:
      name: my-configmap
